package com.example.ratings;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ModelAttribute;

@Controller // This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with / (after Application path)
public class MainController {
  @Autowired // This means to get the bean called employeeRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private EmployeeService employeeService;
  //private EmployeeRepository employeeRepository;
  
  @GetMapping(path="/")
  public String index() {
	  return "home";
  }

  @GetMapping(path="/add")
  public String addNewEmployee(Model model){
    model.addAttribute("employee", new Employee());
    return "add_emp";
  }

  @PostMapping(path="/save")
  public String saveNewEmployee(@ModelAttribute Employee employee){
	employeeService.saveEmployee(employee);
    //employeeRepository.save(employee);
    return "save_emp";
  }

//  @GetMapping(path="/all")
//  public @ResponseBody Iterable<Employee> getAllEmployees() {
//    // This returns a JSON or XML with the users
//    return employeeRepository.findAll();
//  }

  @GetMapping(path="/top-rated")
  public String getTopEmployees(Model model) {
	  model.addAttribute("top5employees", employeeService.top5employees());
	  //model.addAttribute("top5employees", employeeRepository.findTop5ByOrderByRatingDesc());
	  return "rated_employees";
  }
}